CodeNarc Report: Sample Project - Mar 23, 2012 5:51:18 PM

Summary: TotalFiles=7 FilesWithViolations=4 P1=0 P2=9 P3=3

File: org/codenarc/sample/domain/SampleDomain.groovy
    Violation: Rule=EmptyIfStatement P=2 Line=20 Msg=[The if statement is empty] Src=[if (name) {]
    Violation: Rule=EmptyElseBlock P=2 Line=23 Msg=[The else block is empty] Src=[else {]
    Violation: Rule=ImportFromSamePackage P=3 Line=3 Src=[import org.codenarc.sample.domain.OtherDomain]
    Violation: Rule=DuplicateImport P=3 Line=5 Src=[import org.codenarc.sample.other.Other]

File: org/codenarc/sample/service/NewService.groovy
    Violation: Rule=EmptyForStatement P=2 Line=12 Msg=[The for statement is empty] Src=[for(int i=0; i < values.size(); i++) {]
    Violation: Rule=EmptyWhileStatement P=2 Line=18 Msg=[The while statement is empty] Src=[while (!values.empty) {]

File: org/codenarc/sample/service/OtherService.groovy
    Violation: Rule=EmptyTryBlock P=2 Line=10 Msg=[The try block is empty] Src=[try {]
    Violation: Rule=EmptyFinallyBlock P=2 Line=13 Msg=[The finally block is empty] Src=[finally {]
    Violation: Rule=ReturnFromFinallyBlock P=2 Line=24 Msg=[finally statements cannot return a value] Src=[return]

File: org/codenarc/sample/service/SampleService.groovy
    Violation: Rule=EmptyCatchBlock P=2 Line=19 Msg=[The catch block is empty] Src=[} catch(Throwable t) {]
    Violation: Rule=ThrowExceptionFromFinallyBlock P=2 Line=30 Msg=[Throwing an exception from a finally block can hide an underlying error] Src=[throw new Exception('bad stuff')]
    Violation: Rule=UnusedImport P=3 Line=3 Msg=[The [org.codenarc.sample.domain.SampleDomain] import is never referenced] Src=[import org.codenarc.sample.domain.SampleDomain]

[CodeNarc (http://www.codenarc.org) v0.17]
